const MESSAGE_TYPE = {
  USER_SESSION_EXPIRED: "USER_SESSION_EXPIRED",
  MARKET_FEED: "MARKET_FEED",
  BACKTEST: {
    INITIATED: "BACKTEST/INITIATED",
    UPDATE: "BACKTEST/UPDATE",
  },
};

export default {
  MESSAGE_TYPE,
};
