export const WEB_SOCKET = {
  MESSAGE_TYPE: {
    USER_SESSION_EXPIRED: "USER_SESSION_EXPIRED",
    MARKET_FEED: "MARKET_FEED",
    BACKTEST: {
      INITIATED: "BACKTEST/INITIATED",
      UPDATE: "BACKTEST/UPDATE",
    },
    POSITION: {
      UPDATE: (positionId) => `POSITION/UPDATE/${positionId}`,
    },
  },
};
